### ISSUE TITLE
Can't get any brokers or topics listed

### ISSUE THREAD

**Issue by jpotter** [claudemamo/kafka-web-console#34]
We're not able to see anything listed under Brokers or Topics on kafka-web-console. We have two zookeeper nodes in the data center and they show up fine, but the info under the other tabs is just blank.

There's no logging being produced, either, so I'm not even sure how to debug this.

Suggestions?

Thanks!

-Jeff

Some additional info that might help shed some light:

![screen shot 2014-09-10 at 4 20 49 pm](https://cloud.githubusercontent.com/assets/532530/4224780/1f16c5e0-3928-11e4-8dad-416044e60b2e.png)
![screen shot 2014-09-10 at 4 22 06 pm](https://cloud.githubusercontent.com/assets/532530/4224785/286b0bc4-3928-11e4-922d-fe0b84c46c7c.png)

And, in zookeeper, we have plenty of data.

...
├── kafka
│   ├── address_book
│   │   ├── partition_0
│   ├── apns
│   │   ├── partition_0
│   ├── admin
│   │   ├── delete_topics
│   ├── consumers
│   │   ├── kafkaspout
│   │   │   ├── offsets
│   │   │   │   ├── address_book
│   │   │   │   │   ├── 3
│   │   │   │   │   ├── 2
...

**Comment by harshv2** [comment]
Hi,

I'm unable to connect, status is always connecting!! Could anybody help me? Am i missing anything?


![screen shot 2015-03-31 at 4 44 35 pm](https://cloud.githubusercontent.com/assets/3680454/6928959/6bb1e0a6-d7c5-11e4-9e83-cdd86cdc5aa2.png)
