### ISSUE TITLE
Not able to get the graphs showing consumer offset and lag history

### ISSUE THREAD

**Issue by cbalas0** [claudemamo/kafka-web-console#48]
Not able to get the graphs showing consumer offset and lag history as well as consumer/producer message throughput history.

I am using kafka-web-console_2.10-2.1.0-SNAPSHOT and using play-2.2-1 

Thanks In Advance
Chitravel

**Comment by cbalas0** [comment]
Had issue with my evolutions and associated offset sqls. I reran the build in play-2,2-1 with default evolutions and able to get the graphs . Thanks for such a wonderful application!

**Comment by streamnsight** [comment]
can you explain what you did? i have the same problem but not sure how to solve
